# Generated by Django 3.2.8 on 2021-10-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
