# Generated by Django 3.2.8 on 2021-10-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderproduct_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
