# Generated by Django 3.2.8 on 2021-10-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
